version: '2.1'
services:
    grafana:
        container_name: grafana
        image: grafana/grafana
        user: "1000"
        ports:
            - 3000:3000
        volumes:
            - /var/lib/docker/data/grafana:/etc/grafana:rw
            - /var/lib/docker/data/grafana:/var/lib/grafana:rw
            - /etc/timezone:/etc/timezone:ro
        restart: on-failure
        depends_on:
            influxdb:
                condition: service_healthy

    influxdb:
        container_name: influxdb
        image: influxdb:1.8.4
        ports:
            - 8086:8086
        volumes:
            - /var/lib/docker/data/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - /var/lib/docker/data/influxdb:/var/lib/influxdb
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
            interval: 30s
            timeout: 1s
            retries: 24
            
    homeassistant:
        container_name: homeassistant
        image: homeassistant/home-assistant
        network_mode: "host"
        volumes:
            - /var/lib/docker/data/homeassistant:/config
            - /etc/localtime:/etc/localtime:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        restart: on-failure
        depends_on:
            influxdb:
                condition: service_healthy
            mosquitto:
                condition: service_started
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
            interval: 30s
            timeout: 10s
            retries: 6

    node-red:
        container_name: node-red
        image: nodered/node-red
        ports:
            - 1880:1880
        volumes:
            - /var/lib/docker/data/node-red:/data
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: "no" # because the exit code(s) are wrong
        depends_on:
            mosquitto:
                condition: service_started
            homeassistant:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:1880"]
            interval: 30s
            timeout: 10s
            retries: 5

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        user: "1000:1000"
        ports:
            - 1883:1883
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/lib/docker/data/mosquitto:/mosquitto/config:ro
            - /var/lib/docker/data/mosquitto:/mosquitto/data
        restart: on-failure

    portainer:
        container_name: portainer
        image: portainer/portainer-ce
        ports:
            - 9000:9000
        volumes:
            - /var/lib/docker/data/portainer:/data:rw
            - /var/run/docker.sock:/var/run/docker.sock
        restart: "no" # because the exit code(s) are wrong

    dockermon:
        container_name: dockermon
        image: philhawthorne/ha-dockermon
        ports:
            - 8126:8126
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/data/dockermon:/config
        restart: on-failure

networks:
    default:
        driver_opts:
            com.docker.network.bridge.host_binding_ipv4: 192.168.2.1
